---
- name: 🔍 SCAN: Container Image and Dependencies for Vulnerabilities
  hosts: localhost  
  vars:
    image_name: "my-app:latest"  # Имя сканируемого Docker-образа
    requirements_path: "requirements.txt"  # Путь к файлу зависимостей Python

  tasks:
    - name: "1. 🐳 Install Trivy (if not installed)"
      block:
        - name: Download Trivy installer
          ansible.builtin.get_url:
            url: "https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.deb"
            dest: "/tmp/trivy.deb"
            mode: '0755'
        - name: Install Trivy from .deb package
          ansible.builtin.apt:
            deb: "/tmp/trivy.deb"
      become: yes

    - name: "2. 🔎 Scan local Docker image for vulnerabilities with Trivy"
      community.docker.docker_image_info:
        name: "{{ image_name }}"
      register: image_info

    - name: Run Trivy scan and fail if critical vulnerabilities are found
      ansible.builtin.command:
        cmd: "trivy image --exit-code 1 --severity CRITICAL,HIGH {{ image_name }}"
      register: trivy_scan_result
      failed_when:
        - trivy_scan_result.rc != 0
        - "'ERROR' not in trivy_scan_result.stderr"  # Игнорируем ошибки скачивания и т.д., но не ошибки наличия уязвимостей.

    - name: "3. 🐍 Install Safety (Python vulnerability scanner)"
      ansible.builtin.pip:
        name: safety
        state: latest

    - name: "4. 📦 Scan Python dependencies for known vulnerabilities"
      ansible.builtin.command:
        cmd: "safety check --file {{ requirements_path }} --full-report"
      register: safety_scan_result
      failed_when: safety_scan_result.rc != 0
      ignore_errors: yes  # Можно изменить на 'no' для строгого режима

    - name: "5. 📄 Save scan reports as artifacts (for CI/CD)"
      ansible.builtin.copy:
        content: |
          TRIVY SCAN REPORT:
          {{ trivy_scan_result.stdout }}

          SAFETY SCAN REPORT:
          {{ safety_scan_result.stdout }}
        dest: "./security-scan-report-{{ ansible_date_time.epoch }}.txt"
